### ISSUE TITLE
path.join works not correct on Windows: Line 75

### ISSUE THREAD

**Issue by saaivs** [Zooz/aws-s3-multipart-copy#8]
`const encodedSourceKey = encodeURIComponent(path.join(source_bucket, object_key))`

produce wrong path on Wndows and AWS return error : {"message":"Copy Source must mention the source bucket and key: sourcebucket/sourcekey","code":"InvalidArgument"}

Please, fix it as  `const encodedSourceKey = encodeURIComponent(source_bucket + '/' + object_key)`

**Comment by LiadBerko** [comment]
Hi saaivs,
I will fix it shortly.

Thanks!

**Comment by LiadBerko** [comment]
fixed
